homeassistant:
  customize: !include customize.yaml
  
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
 # themes: !include_dir_merge_named themes
  themes: !include themes.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
http: !include ip_bans.yaml
#sensor: !include sensors.yaml


wake_on_lan:


browser_mod:
  prefix: "browser_mod_"

lovelace:
  mode: yaml
  dashboards:
    firemote-dashboard:
      mode: yaml
      title: TV Remotes
      icon: mdi:remote
      show_in_sidebar: true
      filename: dashboards/firemote_swipe.yaml

