- id: '1749181860771'
  alias: Basement lights - off after 15 min no presence
  description: 'Turns off the basement main lights when the presence sensor has been
    clear for 15 minutes.

    '
  triggers:
  - entity_id: binary_sensor.basement_sensors_presence
    to: 'off'
    for: 00:15:00
    trigger: state
  conditions:
  - condition: state
    entity_id: light.basement_main_lights
    state: 'on'
  actions:
  - target:
      entity_id: light.basement_main_lights
    action: light.turn_off
  mode: single
- id: '1749182576630'
  alias: Office - presence not detected
  description: 'If nobody is detected for 3 minutes, switch off the office lights
    and desk fan (but only if either of them is still on).

    '
  triggers:
  - entity_id:
    - binary_sensor.office_sensor_presence
    to: 'off'
    for:
      hours: 0
      minutes: 3
      seconds: 0
    trigger: state
  conditions:
  - condition: or
    conditions:
    - condition: state
      entity_id: switch.office_lights
      state: 'on'
    - condition: state
      entity_id: switch.office_desk_fan
      state: 'on'
  actions:
  - target:
      entity_id:
      - switch.office_lights
      - switch.office_desk_fan
    action: switch.turn_off
    data: {}
  mode: single
- &id001
  id: notify_on_automation_run
  alias: _Notify when automations run (except exclusions)
  description: Sends a notification for all automations unless opted out
  triggers:
  - event_type: automation_triggered
    trigger: event
  conditions:
  - condition: template
    value_template: "{{\n  trigger.event.data.entity_id != this.entity_id and\n  trigger.event.data.entity_id
      not in [\n    'automation.motion_in_kids_hallway_after_8_pm',\n    'automation.garage_alert_if_sub_panel_on_no_presence_repeat',\n
      \   'automation.washing_machine_finishes'\n  ]\n}}\n"
  actions:
  - data:
      title: '{{ trigger.event.data.name }}'
      message: ran at {{ now().strftime('%I:%M %p on %A') }}
    action: notify.mobile_app_matts_iphone_15
  mode: parallel
- *id001
- *id001
- *id001
- id: '1749226428214'
  alias: Office – presence detected
  description: 'Turn on office lights, desk fan, and wake the Mac mini when presence
    is detected.

    '
  triggers:
  - entity_id: binary_sensor.office_sensor_presence
    to: 'on'
    trigger: state
  conditions:
  - condition: state
    entity_id: switch.office_lights
    state: 'off'
  actions:
  - target:
      entity_id: switch.office_lights
    action: switch.turn_on
    data: {}
  - target:
      entity_id: switch.office_desk_fan
    action: switch.turn_on
    data: {}
  - target:
      entity_id: button.mac_mini_wake_on_lan
    action: button.press
    data: {}
  mode: single
- id: '1749584931221'
  alias: Office - cool to 72 °F when window closes & it’s ≥ 85 °F
  description: ''
  triggers:
  - entity_id: binary_sensor.office_window
    from: open
    to: closed
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sensor.office_temperature
    above: 85
  actions:
  - target:
      entity_id: climate.master
    data:
      hvac_mode: cool
    action: climate.set_hvac_mode
  - target:
      entity_id: climate.master
    data:
      temperature: 72
    action: climate.set_temperature
  mode: single
- id: '1749587965332'
  alias: Washing Machine Finishes
  description: Notify when washing machine cycle ends
  triggers:
  - entity_id: sensor.washing_machine_status
    to: Clean
    trigger: state
  conditions: []
  actions:
  - data:
      title: Laundry Done
      message: The washing machine is finished.
    action: notify.mobile_app_matts_iphone_15
  mode: single
- id: '1749610654008'
  alias: Outside Lights - Turn On After Sunset
  description: Turns on all outside area lights 20 minutes after sunset
  triggers:
  - event: sunset
    offset: +00:20:00
    trigger: sun
  conditions: []
  actions:
  - action: light.turn_on
    data: {}
    target:
      area_id: outside
  mode: single
- id: '1749610858393'
  alias: Outside Lights - Turn Off At Sunrise
  description: Turns off all outside lights 1 hour before sunrise
  triggers:
  - event: sunrise
    offset: -01:00:00
    trigger: sun
  conditions: []
  actions:
  - target:
      area_id: outside
    action: light.turn_off
  mode: single
- id: '1749615778461'
  alias: House Lights - Off at 1 AM
  description: ''
  triggers:
  - at: 01:00:00
    trigger: time
  conditions: []
  actions:
  - target:
      entity_id: light.house_lights
    action: light.turn_off
    data: {}
  mode: single
- id: '1749653461959'
  alias: Washing Machine Started
  description: ''
  triggers:
  - entity_id: sensor.washing_machine_current_consumption
    above: 10
    for:
      minutes: 1
    trigger: numeric_state
  actions:
  - entity_id: input_boolean.washing_machine_running
    action: input_boolean.turn_on
  mode: single
- id: '1749661967214'
  alias: Garage - Alert if Sub Panel On & No Presence for 4 Minutes (Repeat)
  description: Repeatedly alerts if garage sub panel power is on while no presence
    is detected, until cleared.
  triggers:
  - entity_id: binary_sensor.basement_sensors_presence
    to: 'off'
    for:
      minutes: 4
    trigger: state
  conditions:
  - condition: state
    entity_id: light.garage_sub_panel_power
    state: 'on'
  actions:
  - repeat:
      sequence:
      - data:
          title: "\U0001F6A8 Garage Alert"
          message: 'No presence in garage for 4+ minutes, and the sub panel is still
            on.

            '
        action: notify.mobile_app_matts_iphone_15
      - delay:
          minutes: 3
      until:
      - condition: or
        conditions:
        - condition: state
          entity_id: binary_sensor.basement_sensors_presence
          state: 'on'
        - condition: state
          entity_id: light.garage_sub_panel_power
          state: unavailable
  mode: single
- id: '1749696745569'
  alias: Motion in Kids Hallway After 8 PM
  description: ''
  triggers:
  - entity_id: binary_sensor.hue_motion_sensor_kids_hallway
    from: 'off'
    to: 'on'
    trigger: state
  conditions:
  - condition: time
    after: '20:00:00'
  actions:
  - data:
      title: Motion Detected
      message: Motion detected in the kids hallway!
    action: notify.mobile_app_matts_iphone_15
  mode: single